{% set name = "pytrends" %}
{% set version = "4.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytrends-{{ version }}.tar.gz
  sha256: a54fc1e3171442b3c8f5c080a5e21df807bc4faad7790cc62b7ddb059eb0a94b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - lxml
    - pandas >=0.25
    - python >={{ python_min }}
    - requests

test:
  imports:
    - pytrends
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dreyco676/pytrends
  summary: Pseudo API for Google Trends
  license: Apache-2.0
  # license file manually packaged. See https://github.com/GeneralMills/pytrends/pull/443
  license_file: LICENSE

extra:
  recipe-maintainers:
    - IlanaRadinsky
